### ISSUE TITLE
GCS Bucket Mover - bucket policy only

### ISSUE THREAD

**Issue by wmuizelaar** [GoogleCloudPlatform/professional-services#327] opened 2019-10-03 09:43 UTC
Hi,

I love the GCS Bucket Mover tool - but would it be possible to use it in combination with the bucket policy only feature? It looks like it now really depends on ACLs to exist or at least be accessible, which isn't the case when bucket policy only is activated.

Thanks,

Wietse

**Comment by lukwam** [comment] 2022-05-11 21:54
I am having the same issue.  Even if I add the `--skip_acl` option, it still attempts to pull the ACLs here:

https://github.com/GoogleCloudPlatform/professional-services/blob/main/tools/gcs-bucket-mover/gcs_bucket_mover/bucket_details.py#L54

which is calling `get_entities` on the storage_object.acl object:

https://googleapis.dev/python/storage/latest/_modules/google/cloud/storage/acl.html#ACL.get_entities

which fails with the error:

```
google.api_core.exceptions.BadRequest: 400 GET https://www.googleapis.com/storage/v1/b/my-gcs-bucket-mover-test-bucket/acl: Cannot get legacy ACL for a bucket that has uniform bucket-level access. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access
```

which is the expected behavior when uniform bucket access is enabled. 

https://cloud.google.com/storage/docs/uniform-bucket-level-access#enabled

I have found that if I first change the bucket to use Fine Grained Access, then the script is able to run.

**Comment by bsikander** [comment] 2022-08-03 13:59
Is there any update on this? I am having the exact issue as above.

**Comment by markueez** [comment] 2022-10-09 09:14
@bsikander @lukwam it seems fixed in the latest commits... however, since I had to fix up py3 compatibility anyway, see my fork @ https://github.com/GoogleCloudPlatform/professional-services/compare/main...markueez:professional-services:py3 -- I just migrated tons of buckets with uniform and obj-level ACL's and everything went OK

**Comment by bsikander** [comment] 2022-10-10 11:20
@markueez is [this](https://github.com/GoogleCloudPlatform/professional-services/pull/878/) the commit which fixes this and allows us to migrate uniform buckets?

**Comment by markueez** [comment] 2022-10-10 19:06
yes, specifically,
https://github.com/GoogleCloudPlatform/professional-services/pull/878/commits/354c58637ecf037022f71659bf35d75732300636#diff-8458a8a84d96e3d265dc65e57007c571525af35dcfceb1732d902fd230bd192fR218

**Comment by bsikander** [comment] 2022-10-14 08:50
cool thanks. Will try it out.

**Comment by agold-rh** [comment] 2023-02-17 16:37
@markueez Do you have any code that should be merged, or should this be closed?

**Comment by markueez** [comment] 2023-02-19 09:00
@agold-rh I think this can be closed (worked for me + original reporter never came back)

**Closed** 2023-02-21 14:55 UTC
