### ISSUE TITLE
ValueError: Unable to get the Filesystem for path gs://XXXXX/XXXXX

### ISSUE THREAD

**Issue by maruthiprithivi** [GoogleCloudPlatform/professional-services#166] opened 2019-01-27 05:05 UTC
Hi Guys,

Trying to follow the data_flow example "data_ingestion.py", but every time I run it I get the following error:

`Traceback (most recent call last):
  File "pipeline01.py", line 115, in <module>
    run()
  File "pipeline01.py", line 97, in run
    | 'Write to BigQuery' >> beam.io.Write(
  File "/usr/local/lib/python2.7/site-packages/apache_beam/io/textio.py", line 522, in __init__
    skip_header_lines=skip_header_lines)
  File "/usr/local/lib/python2.7/site-packages/apache_beam/io/textio.py", line 117, in __init__
    validate=validate)
  File "/usr/local/lib/python2.7/site-packages/apache_beam/io/filebasedsource.py", line 118, in __init__
    self._validate()
  File "/usr/local/lib/python2.7/site-packages/apache_beam/options/value_provider.py", line 124, in _f
    return fnc(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/apache_beam/io/filebasedsource.py", line 175, in _validate
    match_result = FileSystems.match([pattern], limits=[1])[0]
  File "/usr/local/lib/python2.7/site-packages/apache_beam/io/filesystems.py", line 153, in match
    filesystem = FileSystems.get_filesystem(patterns[0])
  File "/usr/local/lib/python2.7/site-packages/apache_beam/io/filesystems.py", line 84, in get_filesystem
    raise ValueError('Unable to get the Filesystem for path %s' % path)
ValueError: Unable to get the Filesystem for path gs://python-dataflow-example/data_files/head_usa_names.csv`

The package versions I have on my machine:
- apache-beam==2.4.0

- google-cloud==0.32.0

- google-cloud-storage==1.6.0

- google-cloud-bigquery==1.1.0

- google-cloud-dataflow==2.4.0

Couldn't spot what I'm missing or doing wrong here.

**Comment by jaketf** [comment] 2019-01-27 14:35
Hi @maruthiprithivi, 

I've run [data_ingestion.py](https://github.com/GoogleCloudPlatform/professional-services/blob/master/examples/dataflow-python-examples/dataflow_python_examples/data_ingestion.py) with the same versions on both Dataflow and Direct Runners and was unable to reproduce the error. 

Can you provide some more details around how you are running this pipeline? Namely what are you specifying for `--input` and `--output`

**Comment by maruthiprithivi** [comment] 2019-01-27 22:44
Hi @jaketf,

This is how i'm running this pipeline:

`python pipeline01.py \
  --project xxxxxxxx \
  --runner DataflowRunner \
  --input gs://del-gcp-dataflow-01/test.csv \
  --output "cust.txns" \
  --staging_location gs://test-user01-del/staging \
  --temp_location gs://test-user01-del/tempLoc`

**Comment by jaketf** [comment] 2019-01-28 15:23
Hey @maruthiprithivi, it looks like you have copied the source code into pipeline01.py? Perhaps you made some other changes to the code. This was intended as an "as is" example for [this codelab](https://www.qwiklabs.com/focuses/3460?locale=en&parent=catalog) (the bigquery schema is hard coded etc.). I'd encourage you to follow the directions for that codelab. A side note, the backslashes aren't necessary if you're executing a single line. I'm going to close this as user error. Please pull down the source code again and run it without modifications. You can re-open if the issue persists.

**Closed by jaketf** 2019-01-28 15:23 UTC

**Comment by maruthiprithivi** [comment] 2019-01-31 11:11
Thank you @jaketf. I think the issue was caused due to incompatibility between the packages I had in my environment. Appreciate the side note, I'm executing them in separate lines. 

I created a new virtual env and installed the packages using the "requirements.txt" and it worked like a charm.
