### ISSUE TITLE
Unable to move bucket within the same project with minimum parameter settings

### ISSUE THREAD

**Issue by darshanrd** [GoogleCloudPlatform/professional-services#472] opened 2020-05-06 16:16 UTC
Step 1 : Clone the below path
https://github.com/GoogleCloudPlatform/professional-services/tree/master/tools/gcs-bucket-mover

Step 2: Install requirements and setup.py

pip2 install -r requirements.txt
python setup.py install

Step 3: Created a simple GCS Bucket with a file and object folder

Step 4 : Have a Service Account with GCS Admin permissions and also infact a Project owner permission to ensure access related issues are met

Step 5 : Trying to run a simple command to move bucket within the same project but with a change of location, passing SA keys, bucket name, source and target project name

"bin/bucket_mover --gcp_source_project_service_account_key pso-wmt-data-b598abd26d18.json --gcp_target_project_service_account_key pso-wmt-data-b598abd26d18.json --location us --storage_class STANDARD --skip_everything gs://darshan-regional-bucket-test pso-wmt-data pso-wmt-data"

Step 6 : Still ask for get_iam_policy policy though the --skip_everything option is used

Example of Output log

Source Project: pso-wmt-data
Source Bucket: gs://darshan-regional-bucket-test
Source Service Account: usertelemetry-sa@pso-wmt-data.iam.gserviceaccount.com
Target Project: pso-wmt-data
Target Bucket: gs://darshan-regional-bucket-test
Target Service Account: usertelemetry-sa@pso-wmt-data.iam.gserviceaccount.com
Traceback (most recent call last):
  File "bin/bucket_mover", line 23, in <module>
    cli.main()
  File "build/bdist.linux-x86_64/egg/gcs_bucket_mover/cli.py", line 215, in main
  File "build/bdist.linux-x86_64/egg/gcs_bucket_mover/bucket_mover_service.py", line 56, in main
  File "build/bdist.linux-x86_64/egg/gcs_bucket_mover/bucket_details.py", line 53, in __init__
AttributeError: 'NoneType' object has no attribute 'get_iam_policy'

**Comment by boredabdel** [comment] 2020-05-08 11:44
Hi,

This is not a bug actually, it's a utilisation problem

First this tool is supposed to be used to move buckets between GCP projects and not within the same project. GCS Storage buckets should have uniq names globally so moving a bucket within the same project would not work

Second you need to provide a lock_file_name when you run the cli, the documentation has a section with an example of how to use a config.yaml file with all the details you need, look at this section "Examples"

Last but not least you should not put gs:// in front of the bucket name

I tested the tool myself and confirmed it works as intended.

I will close this issue, please reach out if you are still facing problems,

**Closed** 2020-05-08 11:44 UTC
