### ISSUE TITLE
gce quota sync takes only Compute engine API metrics

### ISSUE THREAD

**Issue by valafon** [GoogleCloudPlatform/professional-services#713] opened 2021-11-03 07:46 UTC
When I use a script to export quota numbers to stackdriver metrics, only those which are in Compute Engine API Service are exported.
Check screenshot, please - 
https://gyazo.com/442ec9d8e7d40bfaf6c257f7ed41499d
only metrics under Compute Engine API  exported, while Cloud Video Intelligence API is not (and all others expect Compute Engine). I didn't find a special flag to export all metrics from all services. How to export everything on the quota page (https://console.cloud.google.com/iam-admin/quotas)?

**Comment by boredabdel** [comment] 2021-11-15 11:35
Hi,

That's because gce-quota is designed to only export Google Compute Engine (GCE) metrics. It's in the name :)

Closing as the tool is working as intended.

**Closed by boredabdel** 2021-11-15 11:35 UTC
