### ISSUE TITLE
e2e-home-appliance-status-monitoring/ Update to 2021 direly needed

### ISSUE THREAD

**Issue by btshow** [GoogleCloudPlatform/professional-services#601] opened 2021-01-26 21:13 UTC
I tried this very interesting demo.
However, several parts of the code need to be updated/bug fixed to enable running it in year 2021. At least these parts: 

## 1. Tensorflow:
In the tensorflow code I needed to replace tf.contrib.estimator.stop_if_no_increase_hook with tf.estimator.experimental.stop_if_no_increase_hook) 

## 2. IoT Key Generation:
Key Generation for IoT (the following is no longer working:
"ssh-keygen -t rsa -b 4096 -f ./rs256.key
openssl rsa -in ./rs256.key -pubout -outform PEM -out ./rs256.pub")
I replaced it with and it seemingly worked:
openssl genpkey -algorithm RSA -out rsa_private.pem -pkeyopt rsa_keygen_bits:2048 
openssl rsa -in rsa_private.pem -pubout -out rsa_public.pem

## 3.AppEngine code:
There are authentification issues with the appengine (i still have to figure out how to solve these issues, but the app engine log says: 
"WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth" 
and 
"Traceback (most recent call last):
File "/env/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'"

A code update or any help especially on this last app engine errors would be highly appreciated. Thank you.

**Comment by JoseGuilhermeDoZe** [comment] 2021-09-27 17:52
gs://gcp_blog/e2e_demo/ or

gs://gcp_blog/

is not accessible. It is not possible to understand the example provided without the files contained in this folder.
Please, you have any suggestions?

**Comment by iht** [comment] 2021-09-28 07:25
@lerrytang Maybe you can comment on this

**Comment by lerrytang** [comment] 2021-09-29 04:22
I've shared the data with @iht who will transfer that into a publicly accessible storage.
Thanks, Israel!

**Comment by JoseGuilhermeDoZe** [comment] 2021-09-30 12:50
@lerrytang @iht 
Thank you so much mr iht and mr lerrytang. Please is it possible to make the files available? I would very much like to study this specific example. My native language is not English, I apologize for errors

**Comment by JoseGuilhermeDoZe** [comment] 2021-10-29 19:24
@iht , @boredabdel , @lerrytang então? por favor, please, help, socorro .....

**Comment by iht** [comment] 2021-10-29 22:39
We cannot transfer to any bucket to share publicly. I am evaluating if I can upload the data to this repo.

**Comment by JoseGuilhermeDoZe** [comment] 2021-10-31 14:56
@iht  Eu não entendo nada, não sei dizer se vocês são funcionários do google ou se trabalham voluntariamente, não sei dizer se o google pagou vocês para fazerem esses exemplos. Não existe um diagrama que mostre a formatação ou lei de formação dos dados, quais são os dados? Como entender os scripts sem os dados de exemplo? Infelizmente os scripts de exemplos não servem para nada pois a única forma de entendê-los é tendo acesso aos dados de exemplo. As pessoas aqui envolvidas tem os arquivos necessários ao entendimento e a justifica em 2021 é que não tem onde colocar esses exemplos para quem quer estudar os exemplos baixá-los? É lamentável, deixa indignado, triste.

**Comment by iht** [comment] 2021-10-31 15:51
Please have a look at the pull request that I submitted. The sample data is there, and it should be soon in the repo, once the pull request is reviewed and approved. The problem is that the way the examples were initially distributed (using a bucket in GCS) is not possible today, due to some restrictions we have about sharing data publicly.

About diagrams and descriptions of the example, please check the blog post where this example was produced: https://cloud.google.com/blog/products/ai-machine-learning/monitoring-home-appliances-from-power-readings-with-ml

**Comment by JoseGuilhermeDoZe** [comment] 2021-10-31 15:55
Thanks, but current situation is Merging is blocked

**Comment by iht** [comment] 2021-10-31 15:57
All pull requests to this repository must be reviewed by someone different to the author of the pull request. That's why it's blocked. It does not mean it will not be merged. It means it is waiting for some repo owner to review it and approve it.

**Comment by JoseGuilhermeDoZe** [comment] 2021-10-31 15:58
Muito obrigado, thanks, very much.

**Comment by boredabdel** [comment] 2021-11-01 10:32
@iht I merged https://github.com/GoogleCloudPlatform/professional-services/pull/711.

Shall we close this one ?

**Comment by JoseGuilhermeDoZe** [comment] 2021-11-01 10:45
Hi, thanks @boredabdel  , the content files not correct,  132 bytes all files?

-rw-rw-r-- 1 1000 1000 128 nov  1 07:42 appliance_info.csv.bz2
-rw-rw-r-- 1 1000 1000 132 nov  1 07:42 appliance_status_ground_truth.csv.bz2
-rw-rw-r-- 1 1000 1000 130 nov  1 07:42 e2e_demo_sample_output.png.bz2
-rw-rw-r-- 1 1000 1000 132 nov  1 07:42 model.tar.bz2
-rw-rw-r-- 1 1000 1000 133 nov  1 07:42 processed_h2_appliance.csv.bz2
-rw-rw-r-- 1 1000 1000 132 nov  1 07:42 test.csv.bz2
-rw-rw-r-- 1 1000 1000 132 nov  1 07:42 train.csv.bz2
-rw-rw-r-- 1 1000 1000 132 nov  1 07:42 valid.csv.bz2

**Comment by boredabdel** [comment] 2021-11-01 10:51
@iht is this expected ?

**Comment by JoseGuilhermeDoZe** [comment] 2021-11-01 10:58
Hi, @boredabdel , files ok, sorry. Thanks.

**Closed** 2021-11-01 11:12 UTC
